name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Simple JS Action
        id: greet
        # reference to action
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: 'Anthony'
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"